Rename _short_bootstrap_node_ip to _bootstrap_node_ip
At least redis does use redis_bootstrap_node_ip and
_short_bootstrap_node_ip makes no sense anyway?
We moved to the ansible stuff via Id6a7b10acc65ca6cd2135796a80fad0723078871
and I got the following error on my deploy:

    Error: Evaluation Error: Error while evaluating a Function Call, Class[Redis::Sentinel]: parameter 'redis_host' expects a Stdlib::Host = Variant

Problem is that redis::sentinel::redis_host points to redis_bootstrap_node_ip
and that is set to nil now:
[root@overcloud-controller-0 hieradata]# hiera -c /etc/puppet/hiera.yaml redis_bootstrap_node_ip
nil

Change-Id: I9de426d0e3a84237418f4d5c8f476a66b07b4126