Fix readme doc
Recent changes to pypi prevent uploading if the rst has issues.

$ python setup.py check -r -s
running check
warning: check: Title underline too short. (line 42)

warning: check: Title underline too short. (line 42)

error: Please correct your package.

Change-Id: Ia1e014cce3e95ccd065395775370d6c29572466f
Related-Bug: #1774001
(cherry picked from commit 8872187d6771c08e0a49f9800d0e6e45bf4ec72c)