Adds tox environment to test requirements conflicts
Enables developer to check requirements for conflicts instead of letting
him wondering clueless about a Zuul job failure.

Also fixes broken requirements-check job due to sphinx conflict:

ERROR: Could not find a global requirements entry to match package sphinx. If the package is already included in the global list, the name or platform markers there may not match the local settings.

Change-Id: Ia20e7907c3a60727d9402bbec1456eedc7970a51