Heat-agents container: set up trunk repos correctly
I recently hit this error when trying to build the heat-agents container
with trunk repositories:

Error: Package: 1:openstack-puppet-modules-9.3.0-0.20161216011152.8c758d6.el7.centos.noarch (delorean-current)
           Requires: puppet-ec2api

It turns out that the way we set up repositories in the heat-agents
container is different than the way we set up the repositories in
non-containerized developer setups and CI.

This patch makes the trunk repo setup the same as in non-containerized
environments [1].

[1] https://github.com/openstack-infra/tripleo-ci/blob/996fb4e69d7445abc98b31adbe7afcc99c11df15/scripts/tripleo.sh#L261-L279

Change-Id: I5cabfd4ad8809674ea968cebfcae5da6453e8c1a