Ansible json error callback plugin
This callback plugin will write any task errors (that are not
ignore_error: true) to a log file in JSON format.

In later patches, we can add the cli and workflows to make these errors
visible via the Mistral API.

Change-Id: I72a91473511f335f8a0e40c7a786ff927113f26a
(cherry picked from commit 6e363363658e7d2508f2d341d7319c6276072e5b)